"""add column for proteins in food model

Revision ID: 95ac0b29ec2b
Revises: dffe75996704
Create Date: 2023-03-18 20:16:50.929674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95ac0b29ec2b'
down_revision = 'dffe75996704'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('foods', sa.Column('proteins_per_100g', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('foods', 'proteins_per_100g')
    # ### end Alembic commands ###
