"""add status for UserModel

Revision ID: 99daa40e1d1a
Revises: f9c7c49ab575
Create Date: 2023-04-15 18:14:32.460834

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '99daa40e1d1a'
down_revision = 'f9c7c49ab575'
branch_labels = None
depends_on = None


def upgrade():
    # create userstatus enum type
    op.execute("CREATE TYPE userstatus AS ENUM ('basic', 'premium')")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('status', sa.Enum('basic', 'premium', name='userstatus'), nullable=False,
                                     server_default='basic'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'status')
    # ### end Alembic commands ###
