"""make correction on UserModel - delete Boolean

Revision ID: c34b419a2bb8
Revises: f85bedb320ac
Create Date: 2023-04-16 11:10:48.632065

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c34b419a2bb8'
down_revision = 'f85bedb320ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('deleted', sa.Boolean(), nullable=False))
    op.drop_column('users', 'deleted_on')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('deleted_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('users', 'deleted')
    # ### end Alembic commands ###
