"""add created_on for users

Revision ID: c3b4d58baee6
Revises: eccbf8b1b9ee
Create Date: 2023-04-18 07:32:00.875056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3b4d58baee6'
down_revision = 'eccbf8b1b9ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_on')
    op.drop_column('admins', 'created_on')
    # ### end Alembic commands ###
