"""add photo url to RecipeModel

Revision ID: e39f88c3f0bc
Revises: c34b419a2bb8
Create Date: 2023-04-17 09:57:50.183242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e39f88c3f0bc'
down_revision = 'c34b419a2bb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('photo_url', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'photo_url')
    # ### end Alembic commands ###
