"""add photo url to RecipeModel with corrected string length

Revision ID: eccbf8b1b9ee
Revises: e39f88c3f0bc
Create Date: 2023-04-17 10:27:13.129716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eccbf8b1b9ee'
down_revision = 'e39f88c3f0bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('photo_url', sa.String(length=2000), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'photo_url')
    # ### end Alembic commands ###
